# Generated by Django 4.2.1 on 2023-11-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_usuario_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='habitaciones'),
        ),
    ]
