# Generated by Django 4.2.1 on 2023-11-30 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_habitacion_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comedor',
            name='servicio_comedor',
            field=models.CharField(choices=[('Servicio ejecutivo', 'Servicio ejecutivo'), ('Especial', 'Especial'), ('General', 'General')], default='General', max_length=50),
        ),
    ]
